### ISSUE TITLE
make border and fill colors optional for framebox

### ISSUE THREAD

**Issue by isaz** [Omikhleia/ptable.sile#9]
So this looks to be possible according to  [`PathRenderer:draw`](https://github.com/Omikhleia/ptable.sile/blob/9b9ec3bbb5539acb8938fb094a50915facfb4f25/packages/framebox/graphics/renderer.lua#L176) but isn't reflected in the `\framebox` and `\roundbox` commands.

**Comment by Omikhleia** [comment]
Indeed, because we call `PathRenderer:draw` with [values](https://github.com/Omikhleia/ptable.sile/blob/9b9ec3bbb5539acb8938fb094a50915facfb4f25/packages/framebox/init.lua#L140) that were always initialized with a color, e.g. here:

https://github.com/Omikhleia/ptable.sile/blob/9b9ec3bbb5539acb8938fb094a50915facfb4f25/packages/framebox/init.lua#L121-L123

One of the issue was the shadow color, though. We don't compute the exclusion, but just draw to boxes on top of each other. So if the fill color is made optional and a shadow is enabled, it might to lead to the expected result ;)

**Comment by isaz** [comment]
Ha, I guess it's not much of a compromise :)

**Comment by Omikhleia** [comment]
> Ha, I guess it's not much of a compromise :)

It seems it is possible in PDF Graphics to implement a "clipping path". That could be a potential way to only draw the relevant part of the shadow.

**Comment by Omikhleia** [comment]
> It seems it is possible in PDF Graphics to implement a "clipping path".

Confirming the a clipping path works. I'll work on making a clean implementation that I have the basics.
